# Generated by Django 3.1.7 on 2021-06-29 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='manufacturer',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='Manufacturer',
        ),
    ]
