# Generated by Django 3.1.7 on 2021-05-05 16:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Main', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CleaningDetail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('equipment_cleaned_on', models.DateTimeField()),
                ('room_cleaned_on', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='CleanType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('clean_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='LogBook',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('qa_checked_on', models.DateTimeField(blank=True, null=True)),
                ('cleaning_checked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='logbook_cleaning_checked', to=settings.AUTH_USER_MODEL)),
                ('cleaning_details', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='logbook.cleaningdetail')),
                ('product_details', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Main.productgranulation')),
                ('qa_checked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='logbook_qa_checked', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='cleaningdetail',
            name='clean_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='logbook.cleantype'),
        ),
        migrations.AddField(
            model_name='cleaningdetail',
            name='equipment_cleaned_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='cleaningdetail_equipment_cleaned_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cleaningdetail',
            name='room_cleaned_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='cleaningdetail_room_cleaned_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
