# Generated by Django 3.1.7 on 2021-04-26 17:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Main', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CleanType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('clean_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='LogBook',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('qa_checked_on', models.DateTimeField()),
                ('equipment_cleaned_on', models.DateTimeField()),
                ('room_cleaned_on', models.DateTimeField()),
                ('clean_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='logbook.cleantype')),
                ('cleaning_checked_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='logbook_cleaning_checked', to=settings.AUTH_USER_MODEL)),
                ('equipment_clean_done_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='logbook_equipment_clean_done', to=settings.AUTH_USER_MODEL)),
                ('product_details', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Main.productgranulation')),
                ('qa_checked_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='logbook_qa_checked', to=settings.AUTH_USER_MODEL)),
                ('room_clean_done_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='logbook_room_clean_done', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
