# Generated by Django 3.1.7 on 2021-05-05 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logbook', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='logbook',
            name='cleaning_checked_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
